version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=nana@123
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=BNPL
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=nana@123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=BNPL
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
